### ISSUE TITLE
configuration should fail if submodules are not cloned

### ISSUE THREAD

**Issue by tomjnixon** [ebu/libear#12]
If the repository is cloned without `--recursive` and Eigen is installed, then installed Eigen headers may be used; this causes compilation errors, which may be confusing.

This should be detected and cause an error while running cmake.

**Comment by benjamin-weiss** [comment]
So you are thinking about adding something like

```
file(GLOB EIGEN_FILES ${PROJECT_SOURCE_DIR}/submodules/eigen)
list(LENGTH EIGEN_FILES NUMBER_OF_EIGEN_FILES)
if(NUMBER_OF_EIGEN_FILES EQUAL 0)
  message(FATAL_ERROR "Could not find eigen3 submodules. Did you also clone the submodules?")
endif()
```
to the `submodules/eigen3.cmake` file?
