### ISSUE TITLE
The PointSourcePanner base class doesn't have a virtual dtor

### ISSUE THREAD

**Issue by trevorknight** [ebu/libear#56]
PointSourcePanner is used for a base class with virtual methods but doesn't have a virtual destructor and is used as the type in some shared_ptrs, so we get warnings like (`-Wno-non-virtual-dtor` `-Wdelete-non-abstract-non-virtual-dtor`)

Adding `virtual ~PointSourcePanner() {}` fixes them all.

**Comment by tomjnixon** [comment]
Thanks, Warnings should really have been enabled in the CI, i'll get that sorted.

It seems like GCC doesn't warn about this, but clang does. Perhaps because it's actually a false positive given how this is used (these objects are never deleted through a base pointer).

**Comment by trevorknight** [comment]
Thanks for fixing that!

I think the issue arises for example when held in a shared_ptr<PointSourcePanner>

**Comment by tomjnixon** [comment]
No problem. It doesn't occur with shared_ptr because it stores the destructor when it's created (with the type of the derived class).

https://gcc.godbolt.org/z/7fh3fGeve

It doesn't really matter, I was just interested to know why running the tests with valgrind/asan hadn't spotted this.
